# Generated by Django 3.1.7 on 2021-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cityId', models.IntegerField(blank=True, null=True)),
                ('cityName', models.CharField(blank=True, max_length=50, null=True)),
                ('regionName', models.CharField(blank=True, max_length=50, null=True)),
                ('districtName', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
